name: Dynamic CI

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run"
        required: true
        default: "dev"

      file_to_run:
        description: "Select file (app + test files)"
        type: choice
        options:
          - app.py
          - test_app.py
        default: app.py

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install pytest

      - name: Run selected file
        run: python ${{ github.event.inputs.file_to_run }}

      - name: Run pytest (for test file)
        if: ${{ github.event.inputs.file_to_run == 'test_app.py' }}
        run: pytest test_app.py
