name: Dynamic CI

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run code from (dev/feature/main)"
        required: true
        default: "dev"

      run_file:
        description: "File to run"
        required: false
        default: "app.py"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set file
        run: echo "FILE=${{ github.event.inputs.run_file }}" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pytest

      - name: Run selected file
        run: python $FILE

      - name: Run tests
        run: pytest tests/ || echo "No tests found"
