name: Dynamic CI

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Select branch"
        type: choice
        options:
          - main
          - dev
          - feature/test
        default: dev

      program_file:
        description: "Select Program File"
        type: choice
        options:
          - app.py
        default: app.py

      test_file:
        description: "Select Test File"
        type: choice
        options:
          - test_app.py
          - test_math.py
        default: test_app.py

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install pytest

      - name: Run selected file
        run: python ${{ github.event.inputs.file_to_run }}

      - name: Run pytest (for test file)
        if: ${{ github.event.inputs.file_to_run == 'test_app.py' }}
        run: pytest test_app.py

      - name: Select default test case by branch
        run: |
          if [ "${{ github.event.inputs.branch }}" = "main" ]; then
            echo "TEST_FILE=test_math.py" >> $GITHUB_ENV

          elif [ "${{ github.event.inputs.branch }}" = "dev" ]; then
            echo "TEST_FILE=test_large.py" >> $GITHUB_ENV

          else
            echo "TEST_FILE=test_decimal.py" >> $GITHUB_ENV
          fi
